mc: False
is_h4l: True
input_files:
  [
    "/data/shared/hyp_run_3/pp2022/LHC22_highIR/AO2D.root",
  ]
output_dir: "../results/"
output_file: "HypertritonResults_antimatter_h4l"
selection:
  {
    "fPt" : "fPt>1.5",
    "fCosPA" : "fCosPA>0.98",
    "fNSigmaHe": "fNSigmaHe>1.2",
    "fTPCsignalPi": "fTPCsignalPi<1000"
  }
is_matter: "antimatter"
calibrate_he_momentum: True
skip_out_tree: False