mc: False
input_files:
  [
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22m/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22o/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22r/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22t/AO2D_merged.root",
  ]
output_dir: "../results/"
output_file: "HypertritonResults_matter.root"
selection: {
    "fPt": "fPt > 2",
    "fCosPA": "fCosPA > 0.9996",
    "fNSigmaHe": "fNSigmaHe > -1.5",
    "fTPCsignalPi": "fTPCsignalPi < 1000."
  }
is_matter: "matter"
correction_file: "utils/he3_pt_calibration.root"
