do_training: True
do_application: True

input_data_path: ['/data/shared/hyp_run_3/apass4/LHC_22o/AO2D_o_merged.root', '/data/shared/hyp_run_3/apass4/LHC_22t/AO2D_t_merged.root', '/data/shared/hyp_run_3/apass4/LHC_22m/AO2D_m_merged.root', '/data/shared/hyp_run_3/apass4/LHC_22r/AO2D_r_merged.root']
input_mc_path: '/data/shared/hyp_run_3/mc/AO2D_MC_BDT.root'
output_dir : '../results/training_test/'

training_preselections: 'fPt>1 and fTPCsignalPi<1000'
training_variables: ['fDcaV0Daug', 'fDcaHe', 'fDcaPi', 'fCosPA']
test_set_size: 0.5
background_over_signal: 1
random_state: 42


hyperparams:
  max_depth: 2
  learning_rate: 0.01
  n_estimators: 500
  seed: 42