mc : False
input_file : '../data/AO2D_pass2_merged.root'
output_dir : '../results/'
output_file : 'HypertritonResults_antimatter.root'
selection : 'fCosPA > 0.999 & fNSigmaHe > -3 & fNTPCclusHe > 110 & fIsMatter == False & fDcaV0Daug < 0.05'
