mc : False
input_file : '../data/AO2D_pass2_merged.root'
output_dir : '../results/'
output_file : 'HypertritonResults_matter.root'
selection : 'fCosPA > 0.9999 & fNSigmaHe > 1 & fNTPCclusHe > 110 & fIsMatter == True'
