mc: False
input_files_data:
  [
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22m/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22o/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22r/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22t/AO2D_merged.root",
  ]
input_files_mc: ["/data/shared/hyp_run_3/mc/AO2D_anch.root"]
input_analysis_results_file: "/data/shared/hyp_run_3/apass4/new_dataformat/AnalysisResults.root"
output_dir: "../results/"
output_file: "ct_analysis.root"

ct_bins: [2, 4, 6, 8, 20]
bkg_fit_func: "pol1"
signal_fit_function: "dscb"
is_matter: "antimatter"

selection:
  [
    {
      "fPt": "fPt > 1",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000.",
    },
    {
      "fPt": "fPt > 1",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000.",
    },
    {
      "fPt": "fPt > 1",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000.",
    },
    {
      "fPt": "fPt > 1",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000.",
    },
  ]


do_syst: True
bkg_fit_func_syst: ["pol1", "pol2", "expo"]
signal_fit_func_syst: ["gaus", "dscb"]
cut_dict_syst:
  {
    "fCosPA": {"cut_greater": True, "cut_list": [0.98, 0.999, 20]},
     "fPt": {"cut_greater": True, "cut_list": [0.8, 1.3, 10]}
  }

