mc: False
input_files_data:
  [
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22m/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22o/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22r/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22t/AO2D_merged.root",
  ]

input_files_mc: ["/data/shared/hyp_run_3/mc/AO2D_MC.root"]
input_analysis_results_file: "/data/shared/hyp_run_3/apass4/new_dataformat/AnalysisResults.root"
output_dir: "../results/"
output_file: "pt_analysis.root"

pt_bins: [1.5, 2., 2.5, 3, 5]
selection:
  [
    {
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    {
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    {
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    {
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
  ]
bkg_fit_func: "pol1" ## choose between pol1 and pol2 (To be expanded)
is_matter: "antimatter"
pt_correction_file: "utils/he3_pt_calibration.root"
