input_files_data:
  [
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22m/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22o/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22r/AO2D_merged.root",
    "/data/shared/hyp_run_3/apass4/new_dataformat/LHC22t/AO2D_merged.root",
  ]
input_files_mc: ["/data/shared/hyp_run_3/mc/LHC23j6b/AO2D_h3l.root"]
input_analysis_results_file: "/data/shared/hyp_run_3/apass4/new_dataformat/AnalysisResults.root"
output_dir: "../results/"
output_file: "pt_analysis_mat"

pt_bins: [1.5, 2., 2.5, 3, 5]
bkg_fit_func: "pol1"
signal_fit_func: "dscb"
is_matter: "antimatter"
n_bins_mass_data: 40
n_bins_mass_mc: 80

selection:
  [
    {
      "fCosPA": "fCosPA > 0.995",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    {
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    {
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    {
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
  ]

sigma_range_mc_to_data: [[1., 1.5], [1., 1.5], [1., 1.5], [1., 1.5]]

do_syst: False
n_trials: 1000
bkg_fit_func_syst: ["pol1", "expo"]
signal_fit_func_syst: ["dscb"]
cut_dict_syst:
  {
    "fCosPA": {"cut_greater": True, "cut_list": [0.98, 0.999, 50]},
     "fPt": {"cut_greater": True, "cut_list": [0.8, 1.5, 50]},
     "fNSigmaHe": {"cut_greater": True, "cut_list": [-2.5, -2.5, 1]},
      "fTPCsignalPi": {"cut_greater": False, "cut_list": [1000, 1000, 1]},
    #  "fDcaV0Daug": {"cut_greater": False, "cut_list": [0.1, 0.5, 20]}
  }

