mc: True
input_files: ["/data/shared/hyp_run_3/mc/AO2D_MC.root"]
output_dir: "../results/"
output_file: "HypertritonResults_antimatter_MC.root"
is_matter: "antimatter"
selection:
  {
    "fPt": "fPt > 1",
    "fCosPA": "fCosPA > 0.99",
    "fNSigmaHe": "fNSigmaHe > -2.",
    "fTPCsignalPi": "fTPCsignalPi < 1000."
  }
correction_file: "utils/he3_pt_calibration.root"
