mc: False
input_files:
  [
    "/data/shared/hyp_run_3/2023/LHC23l/AO2D_merged.root",
    "/data/shared/hyp_run_3/2023/LHC23k/AO2D_merged.root",
    "/data/shared/hyp_run_3/2023/LHC23r/AO2D_merged.root",
    "/data/shared/hyp_run_3/2023/LHC23s/AO2D_merged.root",
    "/data/shared/hyp_run_3/2023/LHC23u/AO2D_merged.root",
    "/data/shared/hyp_run_3/2023/LHC23v/AO2D_merged.root",
    "/data/shared/hyp_run_3/2023/LHC23y/AO2D_merged.root",
    "/data/shared/hyp_run_3/2023/LHC23za/AO2D_merged.root",
    "/data/shared/hyp_run_3/2023/LHC23zc/AO2D_merged.root",

  ]
output_dir: "../results/"
output_file: "HypertritonResults_antimatter_2023"
selection:
  {
    "fPt": "fPt > 1",
    "fCosPA": "fCosPA > 0.99",
    "fNSigmaHe": "fNSigmaHe > -2.",
    "fTPCsignalPi": "fTPCsignalPi < 1000."
  }
is_matter: "antimatter"