mc : False
input_files : ['/data/shared/hyp_run_3/apass4/LHC_22o/AO2D_o_merged.root', '/data/shared/hyp_run_3/apass4/LHC_22t/AO2D_t_merged.root', '/data/shared/hyp_run_3/apass4/LHC_22m/AO2D_m_merged.root', '/data/shared/hyp_run_3/apass4/LHC_22r/AO2D_r_merged.root']
output_dir : '../results/'
output_file : 'HypertritonResults_matter_pass4.root'
selection : 'fCosPA > 0.9995 & fNSigmaHe > -1 and fTPCsignalPi<1000 and fPt>2'
is_matter : 'matter'
