mc: True
is_h4l: False
input_files: ["/data/shared/hyp_run_3/mc/anchoring_2022_apass4/AO2D_h3l_mc.root"]
# input_files: ["../../test_hyp_task/AO2D_h3l_merg.root"]
output_dir: "../results/mc"
output_file: "HypertritonResults_mc_h3l_new_anch"
is_matter: "both"
selection:
  {
  }