mc : True
input_files : ['/data/shared/hyp_run_3/mc/AO2D_MC_BDT.root']
output_dir : '../results/'
output_file : 'HypertritonResults_antimatter_MC.root'
is_matter : 'antimatter'
selection : 'fPt>1 and fCosPA>0.998 and fNSigmaHe>-2. and fTPCsignalPi<1000'
correction_file: "../results/pt_mass_resolutions.root"
