mc: True
input_files: ["/data/shared/hyp_run_3/mc/AO2D_anch.root"]
output_dir: "../results/mc"
output_file: "HypertritonResults_anch"
is_matter: "both"
selection:
  {
  }
correction_file: "utils/he3_pt_calibration.root"
