mc : False
input_files : ['/data/shared/hyp_run_3/apass4/new_dataformat/LHC22m/AO2D_merged.root',
               '/data/shared/hyp_run_3/apass4/new_dataformat/LHC22o/AO2D_merged.root',
               '/data/shared/hyp_run_3/apass4/new_dataformat/LHC22r/AO2D_merged.root',
               '/data/shared/hyp_run_3/apass4/new_dataformat/LHC22t/AO2D_merged.root']
output_dir : '../results/'
output_file : 'HypertritonResults_antimatter.root'
selection : 'fPt>1.3 and fNSigmaHe>-2. and fTPCsignalPi<1000'
is_matter : 'antimatter'
correction_file: "../results/pt_mass_resolutions.root"
