## choose between matter, antimatter or both
matter_type: "antimatter"

## i/o
input_parquet_data : ['../results/HypertritonResults_antimatter_noCosPA.root.parquet']
input_parquet_mc: '../results/HypertritonResults_antimatter_MC_noCosPA.root.parquet'
input_analysis_results: '/data/shared/hyp_run_3/apass4/AnalysisResults.root'
input_analysis_results_mc: '/data/shared/hyp_run_3/mc/AnalysisResults.root'
output_dir : '../results/training_test'
output_file : 'fit_results_antimat_noCosPA.root'


preselections: "fIsMatter==False"
ml_efficiency_scan: False
input_eff_dir: "../results/training"

