## choose between matter, antimatter or both
matter_type: "antimatter"

## i/o
input_parquet_data : ['../results/HypertritonResults_antimatter.root.parquet']
input_parquet_mc: '../results/HypertritonResults_antimatter_MC.root.parquet'
input_analysis_results: '/data/shared/hyp_run_3/apass4/new_dataformat/AnalysisResults.root'
output_dir : '../results'
output_file : 'fit_results_antimat.root'


preselections: ""
ml_efficiency_scan: False
input_eff_dir: "../results/training"
n_bins: 40

