## choose between matter, antimatter or both
matter_type: "both"

## i/o
input_parquet_data : ['../results/HypertritonResults_antimatter.root.parquet', '../results/HypertritonResults_matter_pass4.root.parquet']
input_parquet_mc: '../results/HypertritonResults_MC.root.parquet'
input_analysis_results: '/data/shared/hyp_run_3/apass4/AnalysisResults.root'
output_dir : '../results/'
output_file : 'fit_results_both.root'


### output histogram settings
histo_maximum: 80