# input_parquet_data : ['../results/HypertritonResults_antimatter.root.parquet', '../results/HypertritonResults_matter_pass4.root.parquet']
input_parquet_data : ['../results/HypertritonResults_antimatter.root.parquet']
# input_parquet_data : ['../results/HypertritonResults_matter_pass4.root.parquet']

input_parquet_mc: '../results/HypertritonResults_MC.root.parquet'
output_dir : '../results/'
output_file : 'fit_results_mat.root'
matter_type: "matter"
hist_maximum: 40