mc : True
input_files : ['~/hyp3/mc/AO2D_merged.root']
output_dir : '~/hyp3/results/'
output_file : 'HypertritonResults_inj_gap_matter.root'
selection : 'fCosPA > 0.9995 & fNSigmaHe > -2 & fNTPCclusHe > 120'
