mc : False
input_files : ['/home/fmazzasc/train_out/LHC_22r/AO2D_LHC_22r.root', '/home/fmazzasc/train_out/LHC_22t/AO2D_LHC_22t.root']
output_dir : '../results/'
output_file : 'HypertritonResults_pass3.root'
selection : 'fCosPA > 0.999  & fNTPCclusHe > 120 & fDcaV0Daug<0.01 & fNSigmaHe > -1. and pt>1 and fDecRad>3'
