mc : False
input_files : ['../data/AO2D_pass4_merged.root']
output_dir : '../results/'
output_file : 'HypertritonResults_antimatter_pass4.root'
selection : 'fCosPA > 0.999 & fNSigmaHe > -2 & fNTPCclusHe > 120'
is_matter : 'antimatter'
