input_file_matter : '../results/HypertritonResults_inj_gap_matter.root'
input_file_antimatter : '../results/HypertritonResults_inj_gap_antimatter.root'
output_dir : '../results'
output_file : 'Efficiency.root'
