mc: False
input_files_data:
  [
  "/data/shared/hyp_run_3/pbpb/pass2_full/AO2D.root",
  ]
input_files_mc: ["/data/shared/hyp_run_3/mc/LHC23j6b/AO2D_h3l.root"]
input_analysis_results_file: "/data/shared/hyp_run_3/apass4/new_dataformat/AnalysisResults.root"
output_dir: "../results/"
output_file: "pt_analysis_pbpb"

pt_bins: [2,3,4,5,6]
bkg_fit_func: "pol2"
signal_fit_func: "dscb"
is_matter: "both"
n_bins_mass_data: 40
n_bins_mass_mc: 80
calibrate_he_momentum: False

selection:
  [
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.9999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    },
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    },
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    },
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    },
  ]

sigma_range_mc_to_data: [[1., 1.5], [1., 1.5], [1., 1.5], [1., 1.5]]

do_syst: False
n_trials: 1000
bkg_fit_func_syst: ["pol1", "expo"]
signal_fit_func_syst: ["dscb"]
cut_dict_syst:
  {
    "fCosPA": {"cut_greater": True, "cut_list": [0.98, 0.999, 50]},
     "fPt": {"cut_greater": True, "cut_list": [0.8, 1.5, 50]},
     "fNSigmaHe": {"cut_greater": True, "cut_list": [-2.5, -2.5, 1]},
      "fTPCsignalPi": {"cut_greater": False, "cut_list": [1000, 1000, 1]},
    #  "fDcaV0Daug": {"cut_greater": False, "cut_list": [0.1, 0.5, 20]}
  }

